# Numpy.random assignment workings notebook

## Explanation of the overall purpose of the numpy.random package -

Python documentation - The python built in random function implements pseudo-randomer number generators for various distributions. 
(Python Docs) - The numpy.random function is known to expand the uses of the python built in random function. It includes functions for generating whole arrays of values from  probably distributions. It is widely used due to the additional functionality available and being more efficient in producing the required results than the built in python function. 

(berk) As we have numerous requires from producing random number data sets for testing this submodule, numpy.random, can be useful on such occasions.

It has various functions each useful in different instances. Some examples will follow -


## Produce table of numpy.random functions

## Simple random data" explanation - 



In [ ]:
Numpy.random assignment workings notebook

Explanation of the overall purpose of the numpy.random package -
Python documentation - The python built in random function implements pseudo-randomer number generators for various distributions. (Python Docs) - The numpy.random function is known to expand the uses of the python built in random function. It includes functions for generating whole arrays of values from probably distributions. It is widely used due to the additional functionality available and being more efficient in producing the required results than the built in python function.
​
(berk) As we have numerous requires from producing random number data sets for testing this submodule, numpy.random, can be useful on such occasions.
​
It has various functions each useful in different instances. Some examples will follow -
​
Produce table of numpy.random functions
Simple random data" explanation -¶
​

# Overall purpose of numpy.random package in Python - 
​
The numpy.random package in python is useful for data analysis due to its ability to generate an array of random numbers using either the "rand(), randn() or randint()" functions.
​
It is particularly useful for hypothesis testing in data analysis due to its ability to provide a test sample of data. Sampling is known to be one of the most important useful factors in determining the accuracy of research during a project. As open source datasets can have a number of outliers or errors it can affect any testing as the results are reflective of the testing and the data used. By ruling out the errors which can be present in open datasets using this package it is more indicative or errors within the hypothesis when testing. This is a major advantage of having access to this package in python for data analysts during testing.
​
​
Use of "Simple Random Data" -
Examples of "Simple Random Data" functions from numpy.random package -
Simple.PNG

Above are the examples of the different functions available in the numpy.random package which fall under the "Simple random data category". They fall under "Simple random data" due to - . Please see below for examples of some of the functions mentioned in the diagram above -

Numpy.Random.Rand -
As mentioned in the diagram above this function provides random values in a given shape in an array. For example the function input below -


# Example 1 - 
import numpy as np
np.random.rand(5,3)
​
array([[0.37264354, 0.14647072, 0.88512348],
       [0.45362676, 0.20223693, 0.22239563],
       [0.98635187, 0.4267969 , 0.54886398],
       [0.15236514, 0.98726247, 0.04101239],
       [0.57456524, 0.98815382, 0.07355501]])

# Example 2 -
np.random.rand(2,2)
​
array([[0.05074761, 0.03660147],
       [0.00967197, 0.42957437]])

# Example 3 -
np.random.rand(1,3)
array([[0.67408564, 0.06129761, 0.62688975]])

Function Output - 
Function Output - As can be seen from the examples above, this function can be useful for producing arrays within a given shape for values between [0, 1)

​